version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/configurator/dashboard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/configurator/dashboard/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/mcp-servers"
    schedule:
      interval: "weekly"
