// SPDX-License-Identifier: MIT
/**
 * Reinstall Service (erase-and-replace)
 *
 * Transactional reinstall/sync for existing dev-suite installations.
 *
 * Strategy: scoped erase + replace.
 *  - The manifest (`.dev-suite-manifest.json`) is the source of truth for what
 *    dev-suite OWNS on disk; `.dev-suite.json` is the source of truth for what
 *    to reinstall (the selection).
 *  - Only manifest-tracked MANAGED files are erased (agents, mcp-server dirs,
 *    rule files). Skills are cleaned + rebuilt by `install()` itself
 *    (`cleanStaleSkills`). Shared files (`CLAUDE.md`, `.claude/settings.json`,
 *    `.mcp.json`) are merged/regenerated by `install()` — never hard-erased.
 *  - User-owned content (`.claude/agents/custom/`, `.claude/skills/custom/`,
 *    files not in the manifest) is never touched.
 *  - Locally modified managed files are surfaced in preview; the user opts out
 *    per file (`keep`) to preserve their edits.
 *  - The whole erase+replace is wrapped in backup + rollback-on-error.
 *
 * This intentionally does NOT reuse `InstallationService.uninstall()`: that
 * removes dev-suite entirely, including the shared substrate a reinstall needs
 * to keep. (It used to be unsafe as well — a recursive delete of
 * `.claude/agents` and `.claude/skills` that took `custom/` with it — which
 * `installation/uninstall.ts` now fixes.)
 */

import * as fs from 'fs';
import * as path from 'path';
import { getLogger } from '../utils/logger.js';
import { resolveProjectPath, PathValidationError } from '../utils/utilities.js';
import { readJsonSync } from '../utils/fs-utils.js';
import {
  DEFAULT_TARGET,
  MCP_SERVERS_DIR,
  getTargetLayout,
  type TargetId,
  type TargetLayout,
} from './targets/target-layout.js';
import { targetPaths } from './targets/target-paths.js';
import { managedSurfaces } from './installation/managed-surfaces.js';
import { resolveProjectTargets } from './installation/uninstall.js';
import { recoverEnvVars, recoverSkillLoadingMode } from './installation/install-recovery.js';
import { isOwnedSkillDirOrTracked, trackedSkillPathsFrom } from './installation/skill-ownership.js';
import { isValidRuleId } from './rules.service.js';
import { InstallationService } from './installation.service.js';
import {
  DEV_SUITE_VERSION,
  loadManifest,
  saveManifest,
  calculateFileHashFromPath,
} from './upgrade/index.js';
import {
  copyDirSync,
  removePathScopedRules,
  validatePathWithinBase,
  validateEntryName,
} from './installation/index.js';
import type {
  InstallConfig,
  DetectionResult,
  FrameworkInfo,
} from '../types.js';
import type {
  ExtendedManifest,
  TrackedFile,
  StackInfo,
  ReinstallPreviewResult,
  ReinstallExecuteRequest,
  ReinstallExecuteResult,
  ReinstallModifiedFile,
  ReinstallHistoryEntry,
  ReinstallFileResolution,
} from '../types/index.js';

const logger = getLogger('ReinstallService');

// Re-exported for the tests and callers that import it from here.
export { managedSurfaces };

const BACKUP_DIR_PREFIX = '.dev-suite-backup-';

/** Selection of components to reinstall. */
interface Selection {
  agents: string[];
  mcpServers: string[];
  rules: string[];
}

export class ReinstallService {
  private installationService = new InstallationService();

  /**
   * Preview a reinstall (read-only, repeatable).
   */
  async previewReinstall(projectPath: string): Promise<ReinstallPreviewResult> {
    projectPath = this.guardPath(projectPath);
    const manifest = loadManifest(projectPath);

    if (!manifest) {
      return {
        hasValidManifest: false,
        reason: 'No dev-suite manifest found. Is dev-suite installed in this project?',
        selection: { agents: [], mcpServers: [], rules: [] },
        modifiedManagedFiles: [],
        orphansToRemove: [],
        filesToReplace: [],
        skillDirsToRebuild: 0,
        requiresIntervention: false,
      };
    }

    const selection = this.resolveSelection(projectPath, manifest);
    const files = manifest.files ?? [];

    const modifiedManagedFiles: ReinstallModifiedFile[] = [];
    const filesToReplace: string[] = [];
    const orphansToRemove: string[] = [];

    for (const file of files) {
      const category = this.classify(file);
      if (category === 'shared' || category === 'skip') continue;

      // Skill dirs aren't tracked with a usable hash (a directory hashes to
      // null), so they never appear as manifest 'skill' entries; they are
      // counted from disk below and always rebuilt by install() — no opt-out.
      if (category === 'skill') continue;

      filesToReplace.push(file.path);

      // Orphan detection
      if (this.isOrphan(file, selection)) {
        orphansToRemove.push(file.path);
      }

      // Drift detection (only meaningful for files that still exist + have a hash)
      const fullPath = this.safe(projectPath, file.path);
      const currentHash = calculateFileHashFromPath(fullPath);

      // A file the user deleted hashes to null and used to fall through both
      // branches, so the preview could report drift but never absence — and the
      // reinstall then silently recreated it with no mention.
      if (!currentHash && file.hash && !fs.existsSync(fullPath)) {
        modifiedManagedFiles.push({
          path: file.path,
          type: file.type,
          manifestHash: file.hash,
          currentHash: '(deleted)',
        });
        continue;
      }

      if (currentHash && file.hash && currentHash !== file.hash) {
        modifiedManagedFiles.push({
          path: file.path,
          type: file.type,
          manifestHash: file.hash,
          currentHash,
        });
      }
    }

    return {
      hasValidManifest: true,
      selection,
      modifiedManagedFiles,
      orphansToRemove,
      filesToReplace,
      skillDirsToRebuild: this.countManagedSkillDirs(projectPath),
      requiresIntervention: modifiedManagedFiles.length > 0,
    };
  }

  /**
   * Execute a reinstall: backup → erase (scoped) → replace → verify, with
   * rollback on any failure.
   */
  async executeReinstall(request: ReinstallExecuteRequest): Promise<ReinstallExecuteResult> {
    const projectPath = this.guardPath(request.projectPath);
    const resolutions = request.resolutions ?? {};
    const shouldBackup = request.createBackup !== false;

    const manifest = loadManifest(projectPath);
    if (!manifest) {
      return this.fail('No dev-suite manifest found. Is dev-suite installed in this project?');
    }

    const selection = this.resolveSelection(projectPath, manifest);

    // Recover install parameters BEFORE erasing anything (they live in files we
    // are about to regenerate).
    const recoveryTargets = resolveProjectTargets(projectPath, manifest);
    const skillLoadingMode = this.recoverSkillLoadingMode(projectPath, recoveryTargets);
    const envVars = this.recoverEnvVars(projectPath, recoveryTargets);
    const detectedStack = this.stackInfoToDetectionResult(manifest.detectedStack);

    // Carry over prior history (install() rewrites the manifest from scratch).
    const priorReinstallHistory = manifest.reinstallHistory ?? [];

    // Determine kept (opt-out) files and snapshot their content.
    const keptFiles: string[] = [];
    const keptSnapshots = new Map<string, Buffer>();
    for (const [relPath, decision] of Object.entries(resolutions)) {
      if ((decision as ReinstallFileResolution) !== 'keep') continue;
      const full = this.safe(projectPath, relPath);
      if (fs.existsSync(full)) {
        keptSnapshots.set(relPath, fs.readFileSync(full));
        keptFiles.push(relPath);
      }
    }

    // ---- Backup ----
    let backupDir: string | undefined;
    if (shouldBackup) {
      try {
        backupDir = this.createReinstallBackup(projectPath, manifest);
      } catch (error) {
        logger.error('Backup failed; aborting reinstall', { error });
        return this.fail(
          `Backup failed, reinstall aborted: ${error instanceof Error ? error.message : String(error)}`
        );
      }
    }

    const orphansRemoved: string[] = [];

    try {
      // ---- ERASE (scoped) ----
      orphansRemoved.push(...this.erase(projectPath, manifest, selection, new Set(keptFiles)));

      // ---- REPLACE ----
      const config: InstallConfig = {
        projectPath,
        agents: selection.agents,
        mcpServers: selection.mcpServers,
        rules: selection.rules,
        // This flow already snapshotted the same surfaces above; a second
        // backup would double the work and leave two backup dirs behind.
        createBackup: false,
        envVars,
        detectedStack,
        skillLoadingMode,
        // Re-target the same assistants the project was installed for, so a
        // reinstall regenerates every target's config, not just Claude Code's.
        targets: manifest.targets,
      };
      await this.installationService.install(config);

      // ---- Restore kept files over the canonical versions ----
      const newManifest = loadManifest(projectPath);
      if (!newManifest) {
        throw new Error('Manifest missing after install — install did not complete');
      }
      for (const relPath of keptFiles) {
        const snapshot = keptSnapshots.get(relPath);
        if (!snapshot) continue;
        const full = this.safe(projectPath, relPath);
        fs.mkdirSync(path.dirname(full), { recursive: true });
        fs.writeFileSync(full, snapshot);
        // Re-track the user's hash so future previews don't flag it forever.
        const keptHash = calculateFileHashFromPath(full);
        const entry = newManifest.files.find(f => f.path === relPath);
        if (entry && keptHash) entry.hash = keptHash;
      }

      // ---- VERIFY ----
      const verifyWarnings = this.verify(projectPath, newManifest, selection);

      // ---- History ----
      const historyEntry: ReinstallHistoryEntry = {
        timestamp: new Date().toISOString(),
        devSuiteVersion: DEV_SUITE_VERSION,
        agentsReinstalled: selection.agents,
        mcpReinstalled: selection.mcpServers,
        orphansRemoved,
        keptFiles,
        backupDir,
      };
      newManifest.reinstallHistory = [...priorReinstallHistory, historyEntry];
      saveManifest(projectPath, newManifest);

      logger.info('Reinstall complete', {
        context: {
          projectPath,
          agents: selection.agents.length,
          mcp: selection.mcpServers.length,
          orphansRemoved: orphansRemoved.length,
          keptFiles: keptFiles.length,
          warnings: verifyWarnings.length,
        },
      });

      return {
        success: true,
        backupDir,
        agentsReinstalled: selection.agents,
        mcpReinstalled: selection.mcpServers,
        orphansRemoved,
        keptFiles,
        verifyWarnings,
        newManifest,
      };
    } catch (error) {
      logger.error('Reinstall failed; attempting rollback', { error });
      let rolledBack = false;
      if (backupDir) {
        try {
          this.rollback(projectPath, backupDir, selection, manifest);
          rolledBack = true;
        } catch (rbError) {
          logger.error('Rollback failed — project may be in a partial state', {
            error: rbError,
            context: { backupDir },
          });
        }
      }
      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
        rolledBack,
        backupDir,
        agentsReinstalled: [],
        mcpReinstalled: [],
        orphansRemoved: [],
        keptFiles: [],
        verifyWarnings: [],
      };
    }
  }

  /**
   * Get reinstall history for a project.
   */
  async getReinstallHistory(projectPath: string): Promise<ReinstallHistoryEntry[]> {
    projectPath = this.guardPath(projectPath);
    const manifest = loadManifest(projectPath);
    return manifest?.reinstallHistory ?? [];
  }

  // ========== Private helpers ==========

  private guardPath(projectPath: string): string {
    if (projectPath.includes('..')) throw new PathValidationError('Path traversal not allowed');
    const resolved = resolveProjectPath(projectPath);
    if (!path.isAbsolute(resolved)) throw new PathValidationError('Path must be rooted');
    return resolved;
  }

  /**
   * SECURITY: build a path from `base` + segments and verify it stays within
   * `base` (rejects `..`, resolves symlinks, prefix-checks). Returns the
   * sanitized absolute path to use at the fs sink. Every fs operation in this
   * service goes through here so a malicious manifest/`.dev-suite.json` cannot
   * read, write, or delete outside the project (or backup) root.
   */
  private safe(base: string, ...segments: string[]): string {
    return validatePathWithinBase(path.join(base, ...segments), base);
  }

  private fail(error: string): ReinstallExecuteResult {
    return {
      success: false,
      error,
      agentsReinstalled: [],
      mcpReinstalled: [],
      orphansRemoved: [],
      keptFiles: [],
      verifyWarnings: [],
    };
  }

  /**
   * Resolve the selection from `.dev-suite.json`, falling back to the manifest
   * if it is missing/corrupt.
   */
  private resolveSelection(projectPath: string, manifest: ExtendedManifest): Selection {
    const devSuiteJson = readJsonSync<{
      agents?: { enabled?: string[] };
      mcpServers?: { enabled?: string[] };
      rules?: { enabled?: string[] };
    }>(this.safe(projectPath, '.dev-suite.json'));

    return {
      agents: devSuiteJson?.agents?.enabled ?? manifest.agents ?? [],
      mcpServers: devSuiteJson?.mcpServers?.enabled ?? manifest.mcpServers ?? [],
      // Rule ids come from the project's own `.dev-suite.json`, which never
      // passed through request validation — filter before they reach a path.
      rules: (devSuiteJson?.rules?.enabled ?? []).filter(isValidRuleId),
    };
  }

  /** Resolve a tracked file's target layout, defaulting for legacy/unknown targets. */
  private layoutFor(target: TargetId | undefined): TargetLayout {
    try {
      return getTargetLayout(target ?? DEFAULT_TARGET);
    } catch {
      return getTargetLayout(DEFAULT_TARGET);
    }
  }

  /**
   * Classify a tracked file into how the reinstall treats it.
   */
  private classify(file: TrackedFile): 'managed-file' | 'mcp-server' | 'skill' | 'shared' | 'skip' {
    if (file.type === 'skill') return 'skill';
    if (file.type === 'mcp-server') return 'mcp-server';
    if (file.type === 'agent') return 'managed-file';
    if (file.type === 'config') {
      // Rule files are managed; settings/mcp/dev-suite config are shared/regenerated.
      // The rules directory is per-target (`.claude/rules`, `.github/instructions`,
      // `.cursor/rules`), so resolve it from the file's own target.
      const rulesDir = this.layoutFor(file.target).rulesDir;
      if (rulesDir && file.path.startsWith(`${rulesDir}/`)) return 'managed-file';
      return 'shared';
    }
    // 'generated' (e.g. _README.md) is regenerated by install() — skip erase.
    return 'skip';
  }

  private componentName(file: TrackedFile): string | null {
    if (file.type === 'agent') {
      // Agent file extensions differ per target — `.md` for Claude Code,
      // `.agent.md` for Copilot. Using a hardcoded `.md` would leave the `.agent`
      // stem on Copilot ids, so orphan detection and selection matching would
      // silently miss every Copilot agent.
      const ext = this.layoutFor(file.target).agentFileExtension ?? '.md';
      return path.basename(file.path, ext);
    }
    if (file.type === 'mcp-server') {
      // .mcp-servers/<name>/...
      const parts = file.path.split(/[\\/]/);
      const idx = parts.indexOf(MCP_SERVERS_DIR);
      const name = idx >= 0 ? parts[idx + 1] : undefined;
      return name ?? null;
    }
    return null;
  }

  /** Distinct MCP server bundle names referenced by the manifest's files. */
  private managedMcpNames(files: TrackedFile[]): string[] {
    const names = new Set<string>();
    for (const file of files) {
      if (file.type === 'mcp-server') {
        const name = this.componentName(file);
        if (name && validateEntryName(name)) names.add(name);
      }
    }
    return [...names];
  }

  /**
   * Count the skill directories a reinstall will rebuild.
   *
   * Ownership comes from the sentinel dev-suite writes into each directory it
   * materialises, or from the manifest for installs that predate it — the same
   * rule `cleanStaleSkills` uses, so this is the true "will be rebuilt" count.
   * It used to be "any direct child containing a SKILL.md", which also counted
   * the user's own skills and promised to rebuild files dev-suite must not touch.
   */
  private countManagedSkillDirs(projectPath: string): number {
    const relSkillsDir = targetPaths(projectPath).relSkillsDir;
    const skillsDir = this.safe(projectPath, relSkillsDir);
    if (!fs.existsSync(skillsDir)) return 0;

    const tracked = trackedSkillPathsFrom(loadManifest(projectPath));

    let count = 0;
    try {
      for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name === 'custom' || !validateEntryName(entry.name)) continue;
        const abs = validatePathWithinBase(path.join(skillsDir, entry.name), skillsDir, false);
        if (isOwnedSkillDirOrTracked(abs, `${relSkillsDir}/${entry.name}`, tracked)) count++;
      }
    } catch {
      return 0;
    }
    return count;
  }


  private isOrphan(file: TrackedFile, selection: Selection): boolean {
    const name = this.componentName(file);
    if (file.type === 'agent') return name !== null && !selection.agents.includes(name);
    if (file.type === 'mcp-server') return name !== null && !selection.mcpServers.includes(name);
    return false;
  }

  /**
   * Scoped erase of managed files. NEVER touches `custom/`, shared files, or
   * untracked user content. Returns the relative paths of orphans removed.
   */
  private erase(
    projectPath: string,
    manifest: ExtendedManifest,
    selection: Selection,
    keptPaths: Set<string>,
  ): string[] {
    const orphansRemoved: string[] = [];
    const erasedMcpDirs = new Set<string>();
    const files = manifest.files ?? [];

    for (const file of files) {
      // Hard safety net: never delete anything under a `custom/` segment.
      if (/(^|[\\/])custom[\\/]/.test(file.path)) continue;
      if (keptPaths.has(file.path)) continue;

      const category = this.classify(file);
      const isOrphan = this.isOrphan(file, selection);

      if (category === 'managed-file') {
        // agent files + .claude/rules/*.md copies
        const full = this.safe(projectPath, file.path);
        if (fs.existsSync(full)) {
          fs.unlinkSync(full);
          if (isOrphan) orphansRemoved.push(file.path);
        }
      } else if (category === 'mcp-server') {
        const name = this.componentName(file);
        if (!name || !validateEntryName(name) || erasedMcpDirs.has(name)) continue;
        erasedMcpDirs.add(name);
        const serverDir = this.safe(projectPath, MCP_SERVERS_DIR, name);
        if (fs.existsSync(serverDir)) {
          fs.rmSync(serverDir, { recursive: true, force: true });
          if (isOrphan) orphansRemoved.push(`${MCP_SERVERS_DIR}/${name}`);
        }
      }
      // 'skill' dirs are cleaned + rebuilt by install()'s cleanStaleSkills.
      // 'shared'/'skip' files are left for install() to merge/regenerate.
    }

    // Remove sentinel-guarded path-scoped rule files (only ours).
    const ruleFiles = manifest.installedRuleFiles ?? [];
    if (ruleFiles.length > 0) {
      removePathScopedRules(projectPath, ruleFiles);
    }

    return orphansRemoved;
  }

  /**
   * Post-install verification. Returns non-fatal warnings; throws on fatal
   * problems (which trigger rollback).
   */
  private verify(
    projectPath: string,
    manifest: ExtendedManifest,
    selection: Selection
  ): string[] {
    const warnings: string[] = [];

    // Check against what was ASKED FOR, not only against what was recorded.
    // Iterating the manifest alone is tautological: a component that failed to
    // install is never tracked, so it is invisible — and a reinstall that had
    // just erased it reported success.
    for (const agentId of selection.agents) {
      const recorded = (manifest.files ?? []).some(
        f => f.type === 'agent' && path.basename(f.path).replace(/\.md$/, '') === agentId
      );
      if (!recorded) {
        throw new Error(
          `Verification failed: agent "${agentId}" was selected but no agent file was installed for it`
        );
      }
    }
    for (const server of selection.mcpServers) {
      if (!validateEntryName(server)) continue;
      if (!fs.existsSync(this.safe(projectPath, MCP_SERVERS_DIR, server))) {
        throw new Error(
          `Verification failed: MCP server "${server}" was selected but ${MCP_SERVERS_DIR}/${server} is missing`
        );
      }
    }

    // Every tracked file must exist.
    for (const file of manifest.files ?? []) {
      const full = this.safe(projectPath, file.path);
      if (!fs.existsSync(full)) {
        throw new Error(`Verification failed: tracked file missing after install: ${file.path}`);
      }
    }

    // .mcp.json must be valid JSON with absolute, existing server entry args.
    const mcpJsonPath = this.safe(projectPath, targetPaths(projectPath).relMcpConfigFile);
    if (fs.existsSync(mcpJsonPath)) {
      let parsed: { mcpServers?: Record<string, { args?: string[] }> };
      try {
        parsed = JSON.parse(fs.readFileSync(mcpJsonPath, 'utf-8'));
      } catch (e) {
        throw new Error(`Verification failed: .mcp.json is not valid JSON: ${e instanceof Error ? e.message : e}`);
      }
      for (const [name, entry] of Object.entries(parsed.mcpServers ?? {})) {
        const scriptArg = entry.args?.find(a => a.endsWith('.js') || a.endsWith('.cjs') || a.endsWith('.mjs'));
        if (scriptArg && !path.isAbsolute(scriptArg)) {
          throw new Error(`Verification failed: .mcp.json server "${name}" uses a non-absolute path: ${scriptArg}`);
        }
        if (scriptArg && !fs.existsSync(scriptArg)) {
          warnings.push(`MCP server "${name}" script not found on disk: ${scriptArg}`);
        }
      }
    }

    return warnings;
  }

  // ---- Backup / rollback ----

  /**
   * Back up everything the reinstall could mutate, across every target in the
   * manifest. Copies each target's config-dir tree (copyDirSync skips
   * node_modules/.git), the standalone config files — including nested ones like
   * Copilot's `.vscode/mcp.json` — and each managed `.mcp-servers/<name>` dir
   * into a timestamped backup dir. Returns the absolute backup dir path.
   */
  private createReinstallBackup(projectPath: string, manifest: ExtendedManifest): string {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const backupDir = this.safe(projectPath, `${BACKUP_DIR_PREFIX}${timestamp}`);
    fs.mkdirSync(backupDir, { recursive: true });

    const { dirs, files } = managedSurfaces(resolveProjectTargets(projectPath, manifest));

    // Config-dir trees (agents, skills, rules, settings, custom/ …)
    for (const dir of dirs) {
      const src = this.safe(projectPath, dir);
      if (fs.existsSync(src)) copyDirSync(src, this.safe(backupDir, dir));
    }

    // Standalone config files (project root + nested, e.g. .vscode/mcp.json).
    // Nested files need their parent recreated inside the backup first.
    for (const rel of files) {
      const src = this.safe(projectPath, rel);
      if (fs.existsSync(src)) {
        const dest = this.safe(backupDir, rel);
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
      }
    }

    // Managed MCP server dirs (node_modules skipped by copyDirSync)
    for (const name of this.managedMcpNames(manifest.files ?? [])) {
      const src = this.safe(projectPath, MCP_SERVERS_DIR, name);
      if (fs.existsSync(src)) {
        copyDirSync(src, this.safe(backupDir, MCP_SERVERS_DIR, name));
      }
    }

    this.pruneOldBackups(projectPath);
    logger.info('Created reinstall backup', { context: { backupDir } });
    return backupDir;
  }

  /**
   * Keep only the most recent backups.
   *
   * They live inside the project, contain the env values the user entered in the
   * wizard, and nothing ever removed them — a project reinstalled weekly grew a
   * directory of credential copies. The newest few are worth keeping; the rest
   * are noise the user did not ask for.
   */
  private pruneOldBackups(projectPath: string, keep = 3): void {
    try {
      const dirs = fs
        .readdirSync(projectPath, { withFileTypes: true })
        .filter(e => e.isDirectory() && e.name.startsWith(BACKUP_DIR_PREFIX))
        .map(e => e.name)
        .sort();
      for (const name of dirs.slice(0, Math.max(0, dirs.length - keep))) {
        fs.rmSync(this.safe(projectPath, name), { recursive: true, force: true });
        logger.info('Removed an old reinstall backup', { context: { backup: name } });
      }
    } catch (error: unknown) {
      logger.warn('Could not prune old reinstall backups', { error });
    }
  }

  /**
   * Restore project state from a backup created by createReinstallBackup.
   * Deletes managed surfaces (removing any partial files the failed install
   * created) then copies the backup tree back.
   */
  private rollback(projectPath: string, backupDir: string, selection: Selection, manifest: ExtendedManifest): void {
    const { dirs, files } = managedSurfaces(resolveProjectTargets(projectPath, manifest));

    // 1. Remove managed surfaces created/mutated during the attempt. Config-dir
    // trees go wholesale; standalone files are removed individually so unrelated
    // content in a shared directory (e.g. the rest of `.vscode/`) is untouched.
    for (const dir of dirs) {
      fs.rmSync(this.safe(projectPath, dir), { recursive: true, force: true });
    }
    for (const rel of files) {
      const p = this.safe(projectPath, rel);
      if (fs.existsSync(p)) fs.rmSync(p, { force: true });
    }
    const mcpNames = new Set<string>(selection.mcpServers);
    for (const name of this.managedMcpNames(manifest.files ?? [])) mcpNames.add(name);
    for (const name of mcpNames) {
      if (!validateEntryName(name)) continue;
      const dir = this.safe(projectPath, MCP_SERVERS_DIR, name);
      if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
    }

    // 2. Copy the backup tree back.
    for (const entry of fs.readdirSync(backupDir, { withFileTypes: true })) {
      if (!validateEntryName(entry.name)) continue;
      const src = this.safe(backupDir, entry.name);
      const dest = this.safe(projectPath, entry.name);
      if (entry.isDirectory()) {
        copyDirSync(src, dest);
      } else {
        fs.copyFileSync(src, dest);
      }
    }
    logger.info('Rolled back reinstall from backup', { context: { backupDir } });
  }

  // ---- Install-parameter recovery ----

  /**
   * Both recoveries read every selected assistant's MCP config, not only Claude
   * Code's `.mcp.json` — a Cursor- or Gemini-only project has none, so the old
   * single-file read wiped every API key the user had entered.
   */
  private recoverSkillLoadingMode(projectPath: string, targets: readonly TargetId[]): 'eager' | 'lazy' {
    return recoverSkillLoadingMode(projectPath, targets);
  }

  private recoverEnvVars(projectPath: string, targets: readonly TargetId[]): Record<string, string> {
    return recoverEnvVars(projectPath, targets);
  }

  /**
   * Convert the manifest's snake_case StackInfo back into the camelCase
   * DetectionResult shape that InstallConfig expects.
   */
  private stackInfoToDetectionResult(stack?: StackInfo): DetectionResult | undefined {
    if (!stack) return undefined;
    const fw = (f?: StackInfo['frontend']): FrameworkInfo | undefined =>
      f ? { framework: f.framework, metaFramework: f.meta_framework, runtime: f.runtime } : undefined;
    return {
      projectType: stack.projectType,
      frontend: fw(stack.frontend),
      backend: fw(stack.backend),
      database: stack.database ? { dbType: stack.database.db_type, orm: stack.database.orm } : undefined,
      testing: stack.testing,
      isMonorepo: false,
      confidence: 1,
    };
  }
}
