/**
 * Never overwrite a file dev-suite did not write.
 *
 * Four writers did an unconditional `fs.writeFileSync` into a path the user may
 * already own — `.gemini/agents/<id>.md`, `.kimi-code/agents/<id>.md`,
 * `.claude/agents/<id>.md` and the path-scoped rule files. A hand-written
 * subagent prompt was replaced with no backup and no report, and then recorded
 * in the manifest as dev-suite's, so a later uninstall deleted what had been the
 * user's file.
 *
 * Gemini and Kimi are the sharp cases: assistant detection pre-selects them
 * *because* the user already has those directories.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { InstallationService } from '../../src/services/installation.service.js';
import {
  readPreviouslyManagedPaths,
  readPreviousFileHashes,
  writeManagedFile,
  DRIFT_BACKUP_DIR,
} from '../../src/services/installation/managed-file.js';
import { calculateFileHash } from '../../src/services/installation/file-operations.js';
import {
  createTempDir,
  cleanupTempDir,
  createMockDevSuiteDir,
  createMockProject,
} from '../test-utils.js';

describe('writeManagedFile', () => {
  let dir: string;
  beforeEach(() => { dir = createTempDir('managed-'); });
  afterEach(() => { cleanupTempDir(dir); });

  const call = (rel: string, content: string, owned: string[]) =>
    writeManagedFile({
      absPath: path.join(dir, rel),
      relPath: rel,
      content,
      previouslyManaged: new Set(owned),
    });

  it('writes a file that does not exist yet', () => {
    expect(call('a/b.md', 'new', [])).toBe('written');
    expect(fs.readFileSync(path.join(dir, 'a/b.md'), 'utf-8')).toBe('new');
  });

  it('replaces a file the previous install recorded', () => {
    fs.writeFileSync(path.join(dir, 'x.md'), 'old');
    expect(call('x.md', 'fresh', ['x.md'])).toBe('replaced');
    expect(fs.readFileSync(path.join(dir, 'x.md'), 'utf-8')).toBe('fresh');
  });

  // Ownership by path alone cannot tell "our file, untouched" from "our file,
  // rewritten by a concurrent agent". With baselines supplied, the second case
  // stops being a silent overwrite.
  describe('drift (baselines supplied)', () => {
    const callWithBaselines = (
      rel: string,
      content: string,
      owned: string[],
      hashes: Record<string, string>,
      acknowledged: Record<string, string> = {}
    ) =>
      writeManagedFile({
        absPath: path.join(dir, rel),
        relPath: rel,
        content,
        previouslyManaged: new Set(owned),
        previousHashes: new Map(Object.entries(hashes)),
        acknowledgedHashes: new Map(Object.entries(acknowledged)),
        projectPath: dir,
      });

    it('backs up and reports a drifted file instead of replacing it silently', () => {
      const ours = 'generated by dev-suite\n';
      fs.writeFileSync(path.join(dir, 'x.md'), 'an agent rewrote this\n');

      const outcome = callWithBaselines('x.md', 'fresh', ['x.md'], {
        'x.md': calculateFileHash(ours),
      });

      expect(outcome).toBe('drifted');
      expect(fs.readFileSync(path.join(dir, 'x.md'), 'utf-8')).toBe('an agent rewrote this\n');
      const backup = path.join(dir, ...DRIFT_BACKUP_DIR.split('/'), 'x.md');
      expect(fs.existsSync(backup)).toBe(true);
      expect(fs.readFileSync(backup, 'utf-8')).toBe('an agent rewrote this\n');
    });

    it('replaces our own file when it still matches the recorded baseline', () => {
      const ours = 'generated by dev-suite\n';
      fs.writeFileSync(path.join(dir, 'x.md'), ours);

      expect(
        callWithBaselines('x.md', 'fresh', ['x.md'], { 'x.md': calculateFileHash(ours) })
      ).toBe('replaced');
      expect(fs.readFileSync(path.join(dir, 'x.md'), 'utf-8')).toBe('fresh');
    });

    it('replaces content a human already ratified', () => {
      const adopted = 'adopted by a human\n';
      fs.writeFileSync(path.join(dir, 'x.md'), adopted);

      expect(
        callWithBaselines(
          'x.md',
          'fresh',
          ['x.md'],
          { 'x.md': calculateFileHash('canonical\n') },
          { 'x.md': calculateFileHash(adopted) }
        )
      ).toBe('replaced');
    });

    it('does not invent drift from a missing baseline', () => {
      fs.writeFileSync(path.join(dir, 'x.md'), 'whatever');
      expect(callWithBaselines('x.md', 'fresh', ['x.md'], {})).toBe('replaced');
    });

    it('does not read a CRLF rewrite as drift', () => {
      const lf = 'line one\nline two\n';
      fs.writeFileSync(path.join(dir, 'x.md'), lf.replace(/\n/g, '\r\n'));
      expect(
        callWithBaselines('x.md', 'fresh', ['x.md'], { 'x.md': calculateFileHash(lf) })
      ).toBe('replaced');
    });
  });

  it('reads baselines and ratifications out of the previous manifest', () => {
    fs.writeFileSync(
      path.join(dir, '.dev-suite-manifest.json'),
      JSON.stringify({
        files: [
          { path: '.claude/agents/a.md', hash: 'h1', type: 'agent' },
          { path: '.claude/agents/b.md', hash: 'h2', acknowledgedHash: 'ack', type: 'agent' },
        ],
      })
    );

    const { hashes, acknowledged } = readPreviousFileHashes(dir);
    expect(hashes.get('.claude/agents/a.md')).toBe('h1');
    expect(acknowledged.get('.claude/agents/b.md')).toBe('ack');
    expect(acknowledged.has('.claude/agents/a.md')).toBe(false);
  });

  it('preserves a file nothing recorded — it is the user\'s', () => {
    fs.writeFileSync(path.join(dir, 'x.md'), 'mine');
    expect(call('x.md', 'theirs', [])).toBe('preserved');
    expect(fs.readFileSync(path.join(dir, 'x.md'), 'utf-8')).toBe('mine');
  });

  it('compares paths in POSIX form regardless of separator', () => {
    fs.mkdirSync(path.join(dir, '.gemini/agents'), { recursive: true });
    fs.writeFileSync(path.join(dir, '.gemini/agents/x.md'), 'old');
    expect(call(path.join('.gemini', 'agents', 'x.md'), 'fresh', ['.gemini/agents/x.md'])).toBe('replaced');
  });
});

describe('readPreviouslyManagedPaths', () => {
  let dir: string;
  beforeEach(() => { dir = createTempDir('prevman-'); });
  afterEach(() => { cleanupTempDir(dir); });

  it('returns an empty set when there is no manifest — a first install owns nothing', () => {
    expect(readPreviouslyManagedPaths(dir).size).toBe(0);
  });

  it('returns an empty set for an unparseable manifest, erring toward preserving', () => {
    fs.writeFileSync(path.join(dir, '.dev-suite-manifest.json'), '{ not json');
    expect(readPreviouslyManagedPaths(dir).size).toBe(0);
  });

  it('reads both the object and the legacy string entry shapes', () => {
    fs.writeFileSync(path.join(dir, '.dev-suite-manifest.json'), JSON.stringify({
      files: [{ path: '.claude/agents/a.md' }, 'AGENTS.md'],
    }));
    const paths = readPreviouslyManagedPaths(dir);
    expect(paths.has('.claude/agents/a.md')).toBe(true);
    expect(paths.has('AGENTS.md')).toBe(true);
  });
});

describe('install() does not clobber agent files the user wrote', () => {
  let svc: InstallationService;
  let devSuiteDir: string;
  let projectDir: string;

  const write = (rel: string, body: string) => {
    const full = path.join(projectDir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, body);
  };
  const read = (rel: string) => fs.readFileSync(path.join(projectDir, rel), 'utf-8');

  beforeEach(() => {
    devSuiteDir = createTempDir('clobber-ds-');
    projectDir = createTempDir('clobber-proj-');
    createMockDevSuiteDir(devSuiteDir);
    createMockProject(projectDir, { packageJson: { name: 'test-project' }, hasGit: true });
    svc = new InstallationService();
    process.env.DEV_SUITE_DIR = devSuiteDir;
  });

  afterEach(() => {
    cleanupTempDir(devSuiteDir);
    cleanupTempDir(projectDir);
    delete process.env.DEV_SUITE_DIR;
  });

  const install = (targets: string[]) =>
    svc.install({
      projectPath: projectDir,
      agents: ['typescript-expert'],
      mcpServers: [],
      envVars: {},
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      targets: targets as any,
    });

  it('does not delete a rule file it just refused to overwrite', async () => {
    // The prune that removes rule files an install no longer writes keys off
    // the list of files written *this run*. A drifted file is deliberately not
    // written, so leaving it out of that list made the same run delete it — the
    // run whose log says the file will be preserved. Worse than the overwrite
    // it replaced: an overwrite is recoverable from the catalog, a delete of
    // the user's edited content is not.
    // `core` agents are always-on and get no path-scoped rule file; a scoped
    // category (testing) is what produces one.
    await svc.install({
      projectPath: projectDir,
      agents: ['vitest-expert'],
      mcpServers: [],
      envVars: {},
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      targets: ['claude-code'] as any,
    });

    const rulesDir = path.join(projectDir, '.claude', 'rules');
    const ruleFile = fs.readdirSync(rulesDir).find(x => x.endsWith('.md'));
    expect(ruleFile, 'the install should have written at least one rule file').toBeDefined();

    const rel = `.claude/rules/${ruleFile}`;
    const edited = read(rel) + '\n<!-- edited by an agent mid-run -->\n';
    write(rel, edited);

    await svc.install({
      projectPath: projectDir,
      agents: ['vitest-expert'],
      mcpServers: [],
      envVars: {},
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      targets: ['claude-code'] as any,
    });

    expect(fs.existsSync(path.join(projectDir, rel)), 'the drifted rule file was deleted').toBe(true);
    expect(read(rel)).toBe(edited);

    // Still ours: dropping it from the manifest would leave it behind on
    // uninstall and un-flag the drift on the next scan.
    const manifest = JSON.parse(
      fs.readFileSync(path.join(projectDir, '.dev-suite-manifest.json'), 'utf-8')
    ) as { installedRuleFiles?: string[]; files: Array<{ path: string; hash?: string }> };
    expect(manifest.installedRuleFiles).toContain(rel);
    const entry = manifest.files.find(x => x.path === rel);
    expect(entry).toBeDefined();
    expect(entry?.hash).not.toBe(calculateFileHash(edited));
  });

  it('keeps a hand-written Gemini subagent prompt', async () => {
    const mine = '---\nname: typescript-expert\n---\nMy own carefully tuned prompt.\n';
    write('.gemini/agents/typescript-expert.md', mine);

    await install(['gemini']);

    expect(read('.gemini/agents/typescript-expert.md')).toBe(mine);
  });

  it('keeps a hand-written Kimi subagent prompt', async () => {
    const mine = '---\nname: typescript-expert\n---\nMine, not yours.\n';
    write('.kimi-code/agents/typescript-expert.md', mine);

    await install(['kimi-code']);

    expect(read('.kimi-code/agents/typescript-expert.md')).toBe(mine);
  });

  it('keeps a hand-written .claude/agents file', async () => {
    const mine = '---\nname: typescript-expert\n---\nHand-written.\n';
    write('.claude/agents/typescript-expert.md', mine);

    await install(['claude-code']);

    expect(read('.claude/agents/typescript-expert.md')).toBe(mine);
  });

  it('does not record a preserved file as its own, so uninstall leaves it too', async () => {
    const mine = '---\nname: typescript-expert\n---\nMine.\n';
    write('.gemini/agents/typescript-expert.md', mine);

    await install(['gemini']);

    const manifest = JSON.parse(read('.dev-suite-manifest.json'));
    const tracked = manifest.files.map((f: { path: string }) => f.path);
    expect(tracked).not.toContain('.gemini/agents/typescript-expert.md');

    await svc.uninstall(projectDir);
    expect(read('.gemini/agents/typescript-expert.md')).toBe(mine);
  });

  it('replaces its own file on a second install when nothing touched it', async () => {
    await install(['gemini']);
    const generated = read('.gemini/agents/typescript-expert.md');

    await install(['gemini']);

    expect(read('.gemini/agents/typescript-expert.md')).toBe(generated);
  });

  it('preserves and backs up its own file when something edited it since', async () => {
    // The fan-out case: an agent rewrote a file dev-suite installed. Ownership
    // by path says "ours, overwrite it", which is how the edit used to be lost
    // silently — no backup, no report. The recorded hash is what distinguishes
    // an untouched file from an edited one.
    await install(['gemini']);
    const generated = read('.gemini/agents/typescript-expert.md');
    const edited = generated + '\nedited by an agent\n';
    write('.gemini/agents/typescript-expert.md', edited);

    await install(['gemini']);

    expect(read('.gemini/agents/typescript-expert.md')).toBe(edited);

    // A copy of what was on disk, so the decision stays reversible.
    const backupRoot = path.join(projectDir, '.dev-suite-backup', 'drift');
    expect(fs.existsSync(backupRoot)).toBe(true);

    // Still ours: it must stay in the manifest, or the orphan pruner would
    // delete the very file the install just refused to overwrite.
    const manifest = JSON.parse(
      fs.readFileSync(path.join(projectDir, '.dev-suite-manifest.json'), 'utf-8')
    ) as { files: Array<{ path: string; hash?: string }> };
    const entry = manifest.files.find(x => x.path === '.gemini/agents/typescript-expert.md');
    expect(entry).toBeDefined();
    // Recorded at the baseline, not at the edited content: adopting the edit
    // here would make the next scan call the file clean.
    expect(entry?.hash).not.toBe(calculateFileHash(edited));
  });

  it('reports the preserved file as a skipped capability rather than staying silent', async () => {
    write('.gemini/agents/typescript-expert.md', 'mine');

    // The adapter surfaces it; assert through the adapter so the reason text is
    // covered even though install() currently only logs the skip list.
    const { GeminiAdapter } = await import('../../src/services/targets/adapters/gemini.adapter.js');
    const { targetPaths } = await import('../../src/services/targets/target-paths.js');

    const agent = {
      id: 'typescript-expert',
      name: 'typescript-expert',
      description: 'TypeScript expert',
      filePath: path.join(devSuiteDir, 'agents', 'core', 'typescript-expert.md'),
      category: 'core',
      skills: [],
      mcpServers: [],
    };

    const result = await new GeminiAdapter().write({
      plan: {
        projectPath: projectDir,
        devSuiteDir,
        agents: ['typescript-expert'],
        mcpServers: [],
        rules: [],
        envVars: {},
        skillLoadingMode: 'eager',
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        agentCatalog: [agent] as any,
        mcpCatalog: [],
        targets: ['gemini'],
        previouslyManaged: new Set<string>(),
        previousAgentFiles: new Map<string, readonly string[]>(),
      },
      paths: targetPaths(projectDir, 'gemini'),
      mcpServers: {},
      manifest: { version: '1', installedAt: '', projectPath: projectDir, agents: ['typescript-expert'], mcpServers: [], rules: [], files: [] },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      extendedManifest: { version: '1', installedAt: '', projectPath: projectDir, agents: [], mcpServers: [], features: {}, files: [], upgradeHistory: [], targets: ['gemini'] } as any,
    });

    const agentSkip = result.skipped.find(s => s.capability === 'agents');
    expect(agentSkip).toBeDefined();
    expect(agentSkip!.reason).toContain('typescript-expert');
    expect(agentSkip!.reason).toContain('not written over');
  });
});
