// SPDX-License-Identifier: MIT
/**
 * Keep secrets, bundles and local backups out of version control.
 *
 * Wizard env values — API keys, database URLs — are written verbatim into every
 * selected assistant's MCP config, and two of those (`.vscode/mcp.json`,
 * `.github/mcp.json`) are files teams routinely commit. Dev-suite also drops
 * timestamped `.dev-suite-backup-*` directories in the project root, which
 * contain the same values and accumulate unboundedly.
 *
 * Nothing warned about either. This appends a marked block to `.gitignore` so a
 * config carrying a credential is not committed by accident, and leaves any
 * existing content untouched.
 *
 * The block is **narrow on purpose**. It used to ignore every MCP config of
 * every selected target as soon as the wizard collected *any* env value, and
 * `KB_REPO_BRANCH` or `DASHBOARD_PORT` was enough to trigger it. Two of those
 * paths are not MCP config at all — `.codex/config.toml` and
 * `.gemini/settings.json` are the assistant's whole project configuration — so
 * a project that set a cache TTL silently stopped sharing its Codex setup, and
 * a fresh `git worktree` came up with no assistant configuration whatsoever.
 * Now only a file that literally contains a value declared `secret: true` is
 * ignored, and `scripts/validate-env-secrets.mjs` is the CI gate that keeps
 * those declarations honest.
 */

import * as fs from 'fs';
import * as path from 'path';
import { getLogger } from '../../utils/logger.js';
import { spawnSync } from 'node:child_process';
import { MCP_SERVERS_DIR, mcpConfigFilesFor, type TargetId } from '../targets/target-layout.js';

const logger = getLogger('Gitignore');

const START = '# --- dev-suite (managed) ---';
const END = '# --- end dev-suite ---';

/**
 * Bundles and runtime artifacts always; an MCP config only when *that file*
 * actually contains a secret literal.
 *
 * `.dev-suite-analytics/` (written by the `documentation` MCP server at runtime)
 * and `.dev-suite-live.json` (written by the Live Performance panel) are
 * produced *after* an install, by processes the install pipeline does not own.
 * They belong to the project's working state, not its committed configuration,
 * and were previously in no ignore list, no backup and no uninstall path.
 *
 * `.mcp-servers/` joins them unconditionally. It is ~15 MB of esbuild bundles
 * copied out of the dev-suite checkout, regenerated by every install, and
 * referenced only by absolute path — committing it buys nothing and it was in
 * no ignore list at all, so it showed up as untracked noise in every
 * `git status` and was one `git add -A` away from being committed.
 */
function entriesFor(targets: readonly TargetId[], configsWithSecrets: readonly string[]): string[] {
  const entries = [
    '.dev-suite-backup-*/',
    // The drift backups go in `.dev-suite-backup/drift/` — no suffix, so the
    // glob above does not match it. Every new writer has to be added here by
    // hand, and this one was missed.
    '.dev-suite-backup/',
    '.dev-suite-analytics/',
    '.dev-suite-live.json',
    // Rewritten by a hook on every turn that touches an API file. Pure working
    // state, and noisy in `git status` if left out.
    '.claude/.ds-api-touched',
    `${MCP_SERVERS_DIR}/`,
  ];

  // Only files proven to carry a secret. The old rule ignored every MCP config
  // of every selected target whenever the wizard collected *any* env value —
  // `KB_REPO_BRANCH` was enough — and two of those files are not MCP config at
  // all: `.codex/config.toml` and `.gemini/settings.json` are the assistant's
  // entire project configuration, which teams do commit on purpose.
  const known = new Set<string>();
  for (const target of targets) {
    for (const file of mcpConfigFilesFor(target)) known.add(file);
  }
  for (const file of configsWithSecrets) if (known.has(file)) entries.push(file);

  return [...new Set(entries)];
}

/**
 * The literal values of the env vars declared `secret: true`.
 *
 * `true`/`false` is the pre-secret-store call shape (`hasSecrets`) and is
 * deprecated: it can only say "something was entered", which is what made the
 * block ignore whole assistant configs over a cache TTL. It is still accepted,
 * and still ignores everything, so an un-migrated caller cannot leak.
 */
export type SecretValues = readonly string[] | boolean;

/**
 * Which of the MCP configs on disk contain one of `secretValues` verbatim.
 *
 * Read from disk rather than inferred from the install plan, because the
 * question the `.gitignore` block answers is about the bytes that exist now:
 * a target whose config write was skipped (an unparseable file left untouched)
 * holds no secret, while a file left over from a previous install may still
 * hold one even if this install collected none. Inference gets both backwards.
 */
export function configsContainingSecrets(
  projectPath: string,
  targets: readonly TargetId[],
  secretValues: SecretValues
): string[] {
  const candidates = new Set<string>();
  for (const target of targets) {
    for (const file of mcpConfigFilesFor(target)) candidates.add(file);
  }

  // Legacy boolean call site (`hasSecrets`): fall back to the old, blunt
  // behaviour rather than to *nothing*. Narrowing the block is a safety
  // improvement only when the caller can say which values are secret; a caller
  // that cannot must keep every config ignored.
  if (typeof secretValues === 'boolean') return secretValues ? [...candidates] : [];

  const values = secretValues.filter(v => typeof v === 'string' && v.trim().length > 0);
  if (values.length === 0) return [];

  const found: string[] = [];
  for (const rel of candidates) {
    const abs = path.join(projectPath, ...rel.split('/'));
    let content: string;
    try {
      if (!fs.existsSync(abs)) continue;
      content = fs.readFileSync(abs, 'utf-8');
    } catch (error: unknown) {
      // Unreadable: assume the worst and keep it ignored. A file we cannot
      // inspect is never worth un-ignoring.
      logger.warn('Could not read an MCP config while scanning for secrets', {
        error,
        context: { file: rel },
      });
      found.push(rel);
      continue;
    }
    if (values.some(value => containsSecretValue(content, value))) found.push(rel);
  }

  return found;
}

/**
 * Every form a secret value can take once a writer has serialised it.
 *
 * The scan compares the value the user typed against the bytes on disk, but no
 * writer stores it verbatim: `.mcp.json` and the other JSON configs go through
 * `JSON.stringify`, `.codex/config.toml` through a TOML string escaper. A
 * password containing a backslash, a quote, a tab or a newline is therefore
 * present in escaped form and a raw `includes` misses it — leaving the file out
 * of the ignore block while it holds the credential. `DATABASE_URL` is the one
 * variable the wizard makes a human type, which is precisely where odd
 * characters come from.
 */
function serialisedForms(value: string): string[] {
  const forms = new Set<string>([value]);

  // JSON string body (what every JSON config writer emits, quotes stripped).
  try {
    forms.add(JSON.stringify(value).slice(1, -1));
  } catch {
    // Not serialisable; the raw form still stands.
  }

  // TOML basic string body: the same escapes JSON uses for the characters that
  // matter here, which is enough to recognise the value.
  forms.add(
    value
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t')
  );

  return [...forms].filter(form => form.length > 0);
}

/** True when `content` holds `value` in any form a writer could have produced. */
function containsSecretValue(content: string, value: string): boolean {
  return serialisedForms(value).some(form => content.includes(form));
}

/**
 * Warn when a file that now carries a secret is already tracked by git.
 *
 * A `.gitignore` entry does nothing for a file git already tracks, and the
 * normal lifecycle produces exactly that: the block tells the user which
 * configs are committable, they commit them, and only later do they add a
 * server that needs a credential. The old blunt rule could not hit this because
 * it ignored every config from the first install, so those files never became
 * tracked — narrowing the block is what exposed it.
 *
 * Reporting only. Running `git rm --cached` on a user's file unasked would be a
 * destructive fix for a problem they may already have handled.
 */
function warnIfTracked(projectPath: string, relPaths: readonly string[]): void {
  if (relPaths.length === 0) return;
  let tracked: string[];
  try {
    const result = spawnSync('git', ['ls-files', '--error-unmatch', '--', ...relPaths], {
      cwd: projectPath,
      encoding: 'utf-8',
      shell: false,
    });
    // Non-zero simply means at least one path is untracked; stdout still lists
    // the tracked ones. No git, or not a repository, leaves stdout empty.
    tracked = (result.stdout || '')
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean);
  } catch {
    return;
  }
  if (tracked.length === 0) return;

  logger.warn(
    'A config that now holds a secret is already tracked by git — the .gitignore entry will not affect it',
    {
      context: {
        files: tracked,
        remedy: 'git rm --cached <file> and rotate the credential if it was pushed',
      },
    }
  );
}

/**
 * Append (or refresh) dev-suite's block in the project `.gitignore`.
 *
 * `secretValues` are the literal values of the env vars the catalog marks
 * `secret: true` (see installation/secret-store.ts). They are used only to
 * decide which files to ignore — never written anywhere — and the block is
 * recomputed from the files on disk on every install, so a config that stops
 * carrying a secret stops being ignored, and one that still carries a literal
 * is never un-ignored.
 *
 * Returns the relative path when the file was written, so the caller can track
 * it. A user who deliberately commits their MCP config can delete the block:
 * dev-suite only rewrites what is between its own markers.
 */
export function updateGitignore(
  projectPath: string,
  targets: readonly TargetId[],
  secretValues: SecretValues = []
): string | null {
  const configsWithSecrets = configsContainingSecrets(projectPath, targets, secretValues);
  const hasSecrets = configsWithSecrets.length > 0;

  // Ignoring a file git already tracks is a no-op, and silence here reads as
  // "handled". Say so instead.
  warnIfTracked(projectPath, configsWithSecrets);
  const entries = entriesFor(targets, configsWithSecrets);
  if (entries.length === 0) return null;

  const file = path.join(projectPath, '.gitignore');
  let existing = '';
  try {
    if (fs.existsSync(file)) existing = fs.readFileSync(file, 'utf-8');
  } catch (error: unknown) {
    logger.warn('Could not read .gitignore', { error, context: { file } });
    return null;
  }

  // Guidance, not decoration: the previous block ignored whole assistant
  // configs without saying so, and users had no way to tell what dev-suite
  // considered committable. Everything a teammate needs — AGENTS.md,
  // .dev-suite.json, .dev-suite-manifest.json, .claude/ — is deliberately left
  // out of this block.
  const note = [
    '# Generated by dev-suite. Local, machine-specific or regenerable only.',
    '# DO commit: AGENTS.md, .dev-suite.json, .dev-suite-manifest.json, the .claude/',
    '# substrate, and every assistant config file not listed below.',
    ...(hasSecrets
      ? [
          '# The MCP config(s) listed below currently hold secret values you entered in',
          '# the wizard. Regenerate them on another checkout instead of committing them.',
        ]
      : []),
  ];
  const block = [START, ...note, ...entries, END].join('\n');

  let next: string;
  const startIdx = existing.indexOf(START);
  const endIdx = existing.indexOf(END);
  if (startIdx >= 0 && endIdx > startIdx) {
    next = existing.slice(0, startIdx) + block + existing.slice(endIdx + END.length);
  } else {
    const separator = existing.length === 0 || existing.endsWith('\n') ? '' : '\n';
    next = `${existing}${separator}${existing.length > 0 ? '\n' : ''}${block}\n`;
  }

  if (next === existing) return '.gitignore';

  try {
    fs.writeFileSync(file, next, 'utf-8');
    logger.info('Updated .gitignore with dev-suite entries', {
      context: { entries: entries.length, hasSecrets },
    });
    return '.gitignore';
  } catch (error: unknown) {
    logger.warn('Could not write .gitignore', { error, context: { file } });
    return null;
  }
}

/**
 * Strip dev-suite's block from `.gitignore` on uninstall.
 *
 * Never deletes the file: it is the user's, and everything outside the markers
 * is theirs. Returns true when something was removed.
 */
export function removeGitignoreBlock(projectPath: string): boolean {
  const file = path.join(projectPath, '.gitignore');
  if (!fs.existsSync(file)) return false;
  try {
    const existing = fs.readFileSync(file, 'utf-8');
    const startIdx = existing.indexOf(START);
    const endIdx = existing.indexOf(END);
    if (startIdx < 0 || endIdx <= startIdx) return false;

    const next = (existing.slice(0, startIdx) + existing.slice(endIdx + END.length))
      .replace(/\n{3,}/g, '\n\n')
      .replace(/^\n+/, '');
    fs.writeFileSync(file, next, 'utf-8');
    return true;
  } catch (error: unknown) {
    logger.warn('Could not strip the dev-suite block from .gitignore', { error });
    return false;
  }
}
